### ISSUE TITLE
Error occurred after updating to 3.3.1

### ISSUE THREAD

**Issue by chriskrycho** [careteditor/caret#453]
The following error has occurred:
```
{
    "message": "this[_0x9622[226]][_0x9622[21]](...)[_0x9622[180]] is not a function",
    "version": "3.3.1",
    "os": "macOS Sierra",
    "path": "Caret.js",
    "code": "this[_0x9622[226]][_0x9622[21]](_0x9622[266])[_0x9622[180]](/\"/g,_0x9622[131])",
    "line": 5,
    "column": 29317,
    "stack": [
        "at _0x25e4x3.value (Caret.js:5:29317)",
        "at new _0x25e4x3 (Caret.js:5:18729)",
        "at file:///Applications/Caret.app/Contents/Resources/app.asar/index.html?startup=%7B%22id%22%3A1%2C%22errors%22%3A%5B%5D%2C%22isMainWindow%22%3Atrue%2C%22openFileRequests%22%3A%5B%5D%7D:28:7"
    ]
}
```

**Comment by astoilkov** [comment]
This won't happen again. We fixed the issue in the latest release. Thanks for reporting.

Closing this issue.
